---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8123'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.6
    ports:
    - 8123:8123
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'mynode'
      # CONTEXTIONARY_URL: contextionary:9999

  # contextionary:
  #   environment:
  #     OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
  #     EXTENSIONS_STORAGE_MODE: weaviate
  #     EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8123
  #     NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
  #     ENABLE_COMPOUND_SPLITTING: 'false'
  #   image: semitechnologies/contextionary:en0.16.0-v1.2.1
  #   ports:
  #   - 9999:9999
...