---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8123'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.6
    ports:
    - 8123:8123
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'mynode'
  query:
    build: qa-service/
    ports:
      - 8000:8000
    depends_on:
      - weaviate
    environment:
      WEAVIATE_HOST: 'http://weaviate'
      WEAVIATE_PORT: '8123'
      COLLECTION_NAME: 'WineReview'
      MODEL_NAME: 'bert-large-uncased-whole-word-masking' #'bert-large-uncased-whole-word-masking-finetuned-squad'
      BATCH_SIZE: 100
      MODEL_BATCH_SIZE: 8
      MAX_NUMBER_OF_DOCUMENTS: 2000
      CONVERSATIONAL_HOST: 'http://conversational'
      CONVERSATIONAL_PORT: '8001'
  conversational:
    build: conversational-service/
    ports:
      - 8001:8001
    depends_on:
      - weaviate
    environment:
      HOST: '0.0.0.0'
      PORT: '8001'
      MODEL_NAME: 'bert-large-uncased-whole-word-masking-finetuned-squad'
  ui:
    build: qa-ui/
    ports:
      - 8501:8501
    depends_on:
      - weaviate
      - query
      - conversational
    environment:
      QUERY_HOST: 'http://query'
      QUERY_PORT: '8000'
      QUERY_ENDPOINT: 'query-text'
...