---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8123'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.6
    ports:
    - 8123:8123
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'mynode'
  query_api:
    build: qa-service/
    ports:
      - 8000:8000
    depends_on:
      - weaviate
    environment:
      WEAVIATE_HOST: 'weaviate'
      WEAVIATE_PORT: '8123'
      COLLECTION_NAME: 'WineReview'
      MODEL_NAME: 'distilbert-base-uncased'
...